# Generated by Django 5.2.16 on 2026-07-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor_name", models.CharField(max_length=100)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Cardiology", "Cardiology"),
                            ("Orthopaedics", "Orthopaedics"),
                            ("Neurology", "Neurology"),
                            ("General Medicine", "General Medicine"),
                            ("Pediatrics", "Pediatrics"),
                        ],
                        max_length=50,
                    ),
                ),
                ("qualification", models.CharField(max_length=100)),
                ("experience", models.PositiveIntegerField()),
                (
                    "consultation_fee",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("mobile_number", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
